version: '3'
services:
  fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    restart: on-failure
    command: uvicorn app.main:app --host 0.0.0.0 --reload
